# questions.toml

"Sora's original KH1 design was based off of what character" = [
    "Mickey Mouse",
    "Cloud Strife",
    "Oswald the Lucky Rabbit",
    "Donald Duck",
]

"What is the name of Kairi's nobody" = [
    "Namine",
    "Kairix",
    "Marluxia",
    "Larxene",
]

"Which KH-original character has had three different voice actors" = [
    "Master Xehanort",
    "Luxord",
    "Xigbar",
    "Master Ava",
]

